### PR TITLE
tensorflow-082922

### PR DESCRIPTION
**Pull request by develone**
09/17/22
~/xx/src-chg-test/pico-tflmicro/build
src tree & examples hello_world, magic_wand, and micro_speech were obtain using
the commanand 08/29/22
* dev090222
  remotes/origin/HEAD -> origin/main
  remotes/origin/dev
  remotes/origin/dev-090222
  remotes/origin/dev090222
  remotes/origin/main
python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py \
  -e hello_world \
  -e micro_speech \
  -e magic_wand \
  -e person_detection \
  /tmp/tflm-tree

git clone git@github.com:develone/pico-tflmicro -b dev090222

cd my-pico-tflmicro/

git clone git@github.com:develone/pico-sdk.git

cd pico-sdk

git submodule update --init

cd ../

mkdir build

cd build

export PICO_SDK_PATH=../pico-sdk/

cmake -DPICO_BOARD=pico ..

start build time 16:50
make

-rw-r--r-- 1 devel devel 1782078 Sep 17 17:14 libpico-tflmicro.a
-rw-r--r-- 1 devel devel  234532 Sep 17 16:51 libpico-tflmicro_test.a

examples/hello_world/
-rwxr-xr-x 1 devel devel  783568 Sep 17 17:37 hello_world.elf

examples/micro_speech/
-rwxr-xr-x 1 devel devel 120116 Sep 17 18:00 audio_provider_test.elf

-rwxr-xr-x 1 devel devel 185784 Sep 17 18:24 audio_provider_mock_test.elf

examples/magic_wand/
-rwxr-xr-x 1 devel devel 417900 Sep 17 18:47 magic_wand_test.elf

rwxr-xr-x 1 devel devel  414996 Sep 17 19:12 magic_wand.elf 

openocd -v
Open On-Chip Debugger 0.11.0-g610f137-dirty (2022-05-03-08:59)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

https://github.com/develone/pico-tflmicro/blob/main/new-run-tests.sh
	
#!/bin/bash
# This script needs to be run from the build folder.
#	cp ../new-run-tests.sh .
#	./new-run-tests.sh

openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/hello_world/hello_world.elf verify reset exit"

sleep 3

openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/micro_speech/audio_provider_test.elf verify reset exit"

sleep 3

openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/micro_speech/audio_provider_mock_test.elf verify reset exit"

sleep 3

openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/magic_wand/magic_wand.elf verify reset exit"

sleep 3

openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/magic_wand/magic_wand_test.elf verify reset exit"

sleep 3

openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/magic_wand/gesture_output_handler_test.elf verify reset exit"

sleep 3

https://github.com/develone/pico-tflmicro/blob/main/new-test-results.txt

### CODE REVIEW

**Comment by aallan** [comment]
It is unclear what this PR does, or even if it was intentional?

**Comment by develone** [comment]
The pull request was an update of tensor flow . the code was fetched from the tfllite-micro. I just add 3 additional examples in micro_!speech

**Comment by lurch** [comment]
> I just add 3 additional examples

:thinking:  
Screenshot from 2022-09-19 14-33-01

**Comment by develone** [comment]
Recognizze_commands,_test and command_responder_test. The file names in update were .cc not .cpp

**Comment by aallan** [comment]
If you want to contribute back to TensorFlow Lite you should look to PR to the upstream Google repository. We're not in a position to accept contributions to this fork, which is specific to RP2040.

**Comment by develone** [comment]
Not sure I understand the process of pull requests. I am new to creating one. My repo is for a rp2040 and I forked this repo. Mine is at pico-tflmicro on develone at github. Any help is appreciated

**Comment by develone** [comment]
Is anyone working on tensorflow for the pico.  This is my latest build https://github.com/develone/devel-pico-tflmicro that can run 9 tests. ./devel-run-tests.sh in the build folder. This take about 3 hours to build on a Raspberry Pi 4 8Gb.  Instead of rp2 my is pico ls ../src/tensorflow/lite/micro/pico/
debug_log.cc  micro_time.cc would be interested in finding system_setup.cc for the pico.  Let me know if I can provide additional information this version has and updated tensorflow obtained on 08/29/22.

**Pull request closed without merging**
